"""Registry of ASF policy documents."""

from __future__ import annotations

# Sources may carry an optional "search_requires" term: search_policies only
# includes (and fetches) such sources when the query mentions that term.
POLICY_SOURCES: dict[str, dict[str, str]] = {
    "pmc": {
        "title": "PMC Guide (Mailing Lists, Committers, PMC Members)",
        "url": "https://www.apache.org/dev/pmc.html",
        "section": "Community And Project Oversight",
        "description": "Rules for mailing lists, adding committers, and managing PMC membership",
    },
    "code_of_conduct": {
        "title": "Code of Conduct",
        "url": "https://www.apache.org/foundation/policies/conduct",
        "section": "Community And Project Oversight",
        "description": "Expected conduct for participants in ASF communities",
    },
    "anti_harassment": {
        "title": "Anti-Harassment Policy",
        "url": "https://www.apache.org/foundation/policies/anti-harassment",
        "section": "Community And Project Oversight",
        "description": "Policy for preventing and responding to harassment in ASF spaces",
    },
    "public_archives": {
        "title": "Public Forum Archive Policy",
        "url": "https://www.apache.org/foundation/public-archives.html",
        "section": "Community And Project Oversight",
        "description": "Policy for archiving ASF public forums such as mailing lists",
    },
    "mailing_lists": {
        "title": "ASF Mailing Lists",
        "url": "https://www.apache.org/foundation/mailinglists.html",
        "section": "Community And Project Oversight",
        "description": "Foundation-wide mailing list index, naming conventions, and usage expectations",
    },
    "bylaws": {
        "title": "Bylaws of The Apache Software Foundation",
        "url": "https://www.apache.org/foundation/bylaws.html",
        "section": "Governance",
        "description": "Foundation bylaws covering membership, directors, officers, PMCs, records, and amendments",
    },
    "certificate_of_incorporation": {
        "title": "Certificate of Incorporation of The Apache Software Foundation",
        "url": "https://www.apache.org/foundation/records/certificate.html",
        "section": "Governance",
        "description": "Founding certificate of incorporation establishing the ASF as a Delaware nonstock membership corporation, including its charitable purpose, members, and directors",
    },
    "board_policy_overview": {
        "title": "Apache Board - Project Services and Expectations",
        "url": "https://www.apache.org/board/policies",
        "section": "Governance",
        "description": "The comprehensive list of MUST/SHOULD/MAY requirements the board and policy-setting officers place on all Apache PMCs",
    },
    "board_escalation": {
        "title": "Board Escalation Guide",
        "url": "https://www.apache.org/board/escalation",
        "section": "Governance",
        "description": "How to escalate serious concerns about Apache projects or officers to the appropriate list",
    },
    "project_independence": {
        "title": "Project Independence",
        "url": "https://community.apache.org/projectIndependence.html",
        "section": "Independence",
        "description": "Guidelines for operating independently and for the public good",
    },
    "board_reporting": {
        "title": "Board Reporting Requirements",
        "url": "https://www.apache.org/foundation/board/reporting",
        "section": "Reporting",
        "description": "Quarterly board status report requirements for PMCs",
    },
    "release_policy": {
        "title": "Release Policy",
        "url": "https://www.apache.org/legal/release-policy",
        "section": "Release",
        "description": "Apache software release policy - what constitutes a valid release",
    },
    "voting": {
        "title": "Apache Voting Process",
        "url": "https://www.apache.org/foundation/voting.html",
        "section": "Release",
        "description": "Apache voting process for releases and other decisions",
    },
    "release_distribution": {
        "title": "Release Distribution Policy",
        "url": "https://infra.apache.org/release-distribution.html",
        "section": "Release",
        "description": "Policy for how and where Apache releases are distributed",
    },
    "docker_hub": {
        "title": "Docker Hub Policy",
        "url": "https://infra.apache.org/docker-hub-policy.html",
        "section": "Release",
        "description": "Policy for Apache projects using Docker Hub",
    },
    "release_download_pages": {
        "title": "Release Download Pages Policy",
        "url": "https://infra.apache.org/release-download-pages.html",
        "section": "Release",
        "description": "Policy for Apache project release download pages",
    },
    "nightlies": {
        "title": "Project Use of nightlies.apache.org",
        "url": "https://infra.apache.org/nightlies.html",
        "section": "Release",
        "description": "Policy for project use of nightlies.apache.org",
    },
    "security": {
        "title": "Security Team Guidance",
        "url": "https://www.apache.org/security/",
        "section": "Security",
        "description": "Security notification and disclosure procedures",
    },
    "security_committers": {
        "title": "Vulnerability Handling for Committers",
        "url": "https://www.apache.org/security/committers.html",
        "section": "Security",
        "description": "How committers should handle reported security vulnerabilities",
    },
    "licenses": {
        "title": "Contributor License Agreements (CLAs)",
        "url": "https://www.apache.org/licenses/",
        "section": "Licensing",
        "description": "CLA requirements and Apache license versions",
    },
    "apply_license": {
        "title": "Applying the Apache License, Version 2.0",
        "url": "https://www.apache.org/legal/apply-license.html",
        "section": "Licensing",
        "description": "Guidance for applying the Apache 2.0 license to ASF work",
    },
    "cla_faq": {
        "title": "CLA FAQ",
        "url": "https://www.apache.org/foundation/license-faq.html",
        "section": "Licensing",
        "description": "Frequently asked questions about Contributor License Agreements",
    },
    "source_headers": {
        "title": "Apache Source Headers",
        "url": "https://www.apache.org/legal/src-headers.html",
        "section": "Licensing",
        "description": "Required Apache license headers in source files",
    },
    "resolved_licenses": {
        "title": "Approved/Resolved Third-Party Licenses",
        "url": "https://www.apache.org/legal/resolved.html",
        "section": "Licensing",
        "description": "Which third-party licenses are Category A (allowed), B (limited), or X (forbidden)",
    },
    "crypto_policy": {
        "title": "Handling Cryptography within an ASF Release",
        "url": "https://infra.apache.org/crypto.html",
        "section": "Licensing",
        "description": "Cryptography policy for ASF releases",
    },
    "export_control": {
        "title": "ASF Export Classifications and Source Links",
        "url": "https://www.apache.org/licenses/exports/",
        "section": "Licensing",
        "description": "U.S. export control status of ASF products and the regulations applying to ASF distributions",
    },
    "generative_tooling": {
        "title": "Generative Tooling Guidance",
        "url": "https://www.apache.org/legal/generative-tooling.html",
        "section": "Licensing",
        "description": "Guidance for using generative tooling in ASF work",
    },
    "dmca": {
        "title": "DMCA Designated Agent",
        "url": "https://www.apache.org/legal/dmca",
        "section": "Licensing",
        "description": "The ASF's Digital Millennium Copyright Act designated agent and the process for DMCA notices",
    },
    "branding": {
        "title": "Project Branding Requirements",
        "url": "https://www.apache.org/foundation/marks/pmcs",
        "section": "Branding",
        "description": "Trademark and branding requirements for PMC projects",
    },
    "trademark_maintenance": {
        "title": "Trademark Maintenance Responsibilities",
        "url": "https://www.apache.org/foundation/marks/responsibility.html",
        "section": "Branding",
        "description": "PMC responsibilities for maintaining Apache trademarks",
    },
    "website_linking": {
        "title": "Website Linking Policy",
        "url": "https://www.apache.org/foundation/marks/linking",
        "section": "Branding",
        "description": "Policy on linking to and from Apache project websites",
    },
    "event_branding": {
        "title": "Third-Party Event Branding Policy",
        "url": "https://www.apache.org/foundation/marks/events",
        "section": "Branding",
        "description": "Branding policy for third-party events using Apache marks",
    },
    "merchandise_branding": {
        "title": "Non-Software Merchandise Branding Policy",
        "url": "https://www.apache.org/foundation/marks/merchandise",
        "section": "Branding",
        "description": "Branding policy for non-software merchandise using Apache marks",
    },
    "domain_name_branding": {
        "title": "Domain Name Branding Policy",
        "url": "https://www.apache.org/foundation/marks/domains",
        "section": "Branding",
        "description": "Trademark policy for domain names using Apache marks",
    },
    "downstream_distribution": {
        "title": "Apache Software Downstream Distribution Policy",
        "url": "https://www.apache.org/foundation/marks/downstream",
        "section": "Branding",
        "description": "Trademark policy for downstream distributions of Apache software",
    },
    "podling_branding": {
        "title": "Incubator Podling Branding Guide",
        "url": "https://incubator.apache.org/guides/branding.html",
        "section": "Branding",
        "description": "Branding requirements for Apache Incubator podlings",
    },
    "naming_policy": {
        "title": "Process For Selecting New Apache Software Product Names",
        "url": "https://www.apache.org/foundation/marks/naming",
        "section": "Branding",
        "description": "How Apache project and product names are chosen, researched, and cleared, including the trademark research steps required before adopting a name",
    },
    "trademark_reporting": {
        "title": "Trademark Problem/Infringement Reporting Process",
        "url": "https://www.apache.org/foundation/marks/reporting",
        "section": "Branding",
        "description": "How PMCs and third parties report suspected misuse of Apache marks to Brand Management",
    },
    "social_media_branding": {
        "title": "Social Media Best Practices",
        "url": "https://www.apache.org/foundation/marks/socialmedia",
        "section": "Branding",
        "description": "Guidance for projects running branded social media accounts under ASF trademark policy",
    },
    "trademark_name_guide": {
        "title": "Apache Product Name Usage Guide",
        "url": "https://www.apache.org/foundation/marks/guide",
        "section": "Branding",
        "description": "How to correctly refer to Apache brands and product names in text",
    },
    "trademark_faq": {
        "title": "Apache Trademark Usage FAQs",
        "url": "https://www.apache.org/foundation/marks/faq",
        "section": "Branding",
        "description": "Frequently asked questions on permitted and prohibited uses of Apache marks, including Powered By naming",
    },
    "trademark_list": {
        "title": "List of Apache Registered Trademarks",
        "url": "https://www.apache.org/foundation/marks/list",
        "section": "Branding",
        "description": "The authoritative list of ASF word marks and registered trademarks",
    },
    "trademark_policy": {
        "title": "ASF Trademark Policy",
        "url": "https://www.apache.org/foundation/marks/",
        "section": "Branding",
        "description": "Foundation-wide trademark policy and guidance for Apache marks",
    },
    "event_code_of_conduct": {
        "title": "Event Code of Conduct",
        "url": "https://www.apachecon.com/conduct.html",
        "section": "Events",
        "description": "Code of conduct for ASF events such as ApacheCon and Community Over Code",
    },
    "conference_policy": {
        "title": "ASF Conferences",
        "url": "https://www.apache.org/foundation/conferences.html",
        "section": "Events",
        "description": "Official ASF conference policy and the role of the Trademarks Committee in approving event use of Apache marks",
    },
    "repo_policy": {
        "title": "Repository Policy",
        "url": "https://infra.apache.org/project-repo-policy.html",
        "section": "Infrastructure",
        "description": "Policy for project source code repositories",
    },
    "infra_site_ban": {
        "title": "Site-Wide Ban",
        "url": "https://infra.apache.org/infra-ban.html",
        "section": "Infrastructure",
        "description": "Infrastructure policy for site-wide bans",
    },
    "committer_outreach": {
        "title": "Outreach to Committers",
        "url": "https://infra.apache.org/committer-outreach.html",
        "section": "Infrastructure",
        "description": "Policy for Infra outreach to committers",
    },
    "content_moderation": {
        "title": "Content Moderation",
        "url": "https://infra.apache.org/content-moderation.html",
        "section": "Infrastructure",
        "description": "Infrastructure content moderation policy",
    },
    "mail_rejection": {
        "title": "Mail Rejection Policy",
        "url": "https://infra.apache.org/mail-rejection.html",
        "section": "Infrastructure",
        "description": "Policy for rejecting mail sent through ASF infrastructure",
    },
    "spam_reporting": {
        "title": "Dealing with Spam in Your ASF Email Account",
        "url": "https://infra.apache.org/spam-reporting.html",
        "section": "Infrastructure",
        "description": "Policy and process for spam in ASF email accounts",
    },
    "password_policy": {
        "title": "Password Requirements",
        "url": "https://infra.apache.org/password-policy.html",
        "section": "Infrastructure",
        "description": "Password requirements for ASF accounts",
    },
    "third_party_services": {
        "title": "Policy on Issues in Third-Party Services",
        "url": "https://infra.apache.org/third-party-policy.html",
        "section": "Infrastructure",
        "description": "Policy for issues involving third-party services used by ASF projects",
    },
    "slack_policy": {
        "title": "Policy for Using ASF Slack",
        "url": "https://infra.apache.org/slack-policy.html",
        "section": "Infrastructure",
        "description": "Policy for using ASF Slack workspaces",
    },
    "sensitive_information": {
        "title": "Policy on Sharing Sensitive Information with Infra",
        "url": "https://infra.apache.org/sensitive_info.html",
        "section": "Infrastructure",
        "description": "Policy for sharing sensitive information with ASF Infrastructure",
    },
    "github_actions": {
        "title": "GitHub Actions",
        "url": "https://infra.apache.org/github-actions-policy.html",
        "section": "Infrastructure",
        "description": "Policy for Apache projects using GitHub Actions",
    },
    "website_policy": {
        "title": "Website Policy",
        "url": "https://infra.apache.org/project-site-policy.html",
        "section": "Infrastructure",
        "description": "Policy for project websites and hosting",
    },
    "content_security_policy": {
        "title": "Content Security Policy",
        "url": "https://infra.apache.org/csp.html",
        "section": "Infrastructure",
        "description": "Content Security Policy guidance for Apache project websites",
    },
    "app_upgrade_policy": {
        "title": "Application Upgrades",
        "url": "https://infra.apache.org/app-upgrade-policy.html",
        "section": "Infrastructure",
        "description": "Infrastructure policy for application upgrades",
    },
    "backup_policy": {
        "title": "Backups",
        "url": "https://infra.apache.org/backup-policy.html",
        "section": "Infrastructure",
        "description": "Infrastructure backup policy for systems and content",
    },
    "os_upgrade_policy": {
        "title": "Operating System Upgrades",
        "url": "https://infra.apache.org/os-upgrade-policy.html",
        "section": "Infrastructure",
        "description": "Infrastructure policy for operating system upgrades",
    },
    "vm_policy": {
        "title": "Virtual Machines for Projects",
        "url": "https://infra.apache.org/vm-policy.html",
        "section": "Infrastructure",
        "description": "Policy for project virtual machines managed by ASF Infrastructure",
    },
    "jira_account_approval": {
        "title": "Approving Jira Account Requests",
        "url": "https://infra.apache.org/jira-approve-account.html",
        "section": "Infrastructure",
        "description": "Policy for approving Jira account requests",
    },
    "jira_account_retention": {
        "title": "Jira Account Retention Policy",
        "url": "https://infra.apache.org/jira-account-retention-policy.html",
        "section": "Infrastructure",
        "description": "Policy for Jira account retention",
    },
    "press": {
        "title": "Press & Marketing Policy",
        "url": "https://www.apache.org/press/",
        "section": "Press",
        "description": "Guidelines for press releases and marketing coordination",
    },
    "officer_speaking_guide": {
        "title": "Speaking Guidelines for ASF Directors and Officers",
        "url": "https://apache.org/press/guides/officer-speaking-guide.html",
        "section": "Press",
        "description": "When directors, officers, and project leaders speak for the ASF versus themselves, and how to declare a hat in external communications",
    },
    "sponsorship": {
        "title": "Sponsorship Requirements",
        "url": "https://www.apache.org/foundation/sponsorship.html",
        "section": "Fundraising",
        "description": "Fundraising and sponsorship policies",
    },
    "targeted_sponsorship": {
        "title": "Targeted Sponsorship Policy",
        "url": "https://apache.org/foundation/docs/targeted-sponsorship-policy.html",
        "section": "Fundraising",
        "description": "Policy governing the use of targeted sponsorship funds for specific ASF initiatives",
    },
    "privacy": {
        "title": "Privacy Policy",
        "url": "https://privacy.apache.org/policies/privacy-policy-public.html",
        "section": "Privacy",
        "description": "ASF privacy policy",
    },
    "privacy_contributors": {
        "title": "Privacy Policy for Contributors",
        "url": "https://privacy.apache.org/policies/privacy-policy-contributors.html",
        "section": "Privacy",
        "description": "Privacy policy for ASF contributors",
    },
    "privacy_committers": {
        "title": "Privacy Policy for Committers",
        "url": "https://privacy.apache.org/policies/privacy-policy-committer.html",
        "section": "Privacy",
        "description": "Privacy policy for ASF committers",
    },
    "privacy_project_websites": {
        "title": "Privacy Policy for Project Websites",
        "url": "https://privacy.apache.org/policies/website-policy.html",
        "section": "Privacy",
        "description": "Privacy policy for Apache project websites",
    },
    "privacy_downloadable_products_high": {
        "title": "Privacy Policy for ASF Downloadable Applications (High Privacy Standards)",
        "url": "https://privacy.apache.org/policies/privacy-products-policy-high.html",
        "section": "Privacy",
        "description": "Privacy policy for downloadable Apache applications with high privacy standards",
    },
    "privacy_downloadable_products_medium": {
        "title": "Privacy Policy for Products with Medium Privacy Standards",
        "url": "https://privacy.apache.org/policies/privacy-products-policy-medium.html",
        "section": "Privacy",
        "description": "Privacy policy for downloadable Apache products with medium privacy standards",
    },
    "privacy_mailing_lists": {
        "title": "Mailing List Privacy Policy",
        "url": "https://privacy.apache.org/policies/mailinglist-policy.html",
        "section": "Privacy",
        "description": "Privacy policy for ASF public mailing lists",
    },
    "incubator": {
        "title": "Incubator Podling Policies",
        "url": "https://incubator.apache.org/policy/incubation.html",
        "section": "Incubator",
        "description": "Policies governing Apache Incubator podlings",
    },
    "incubator_ip_clearance": {
        "title": "Incubator IP Clearance",
        "url": "https://incubator.apache.org/ip-clearance/",
        "section": "Incubator",
        "description": "Policy and process for IP clearance in the Apache Incubator",
    },
}

# Delaware General Corporation Law (Title 8, Chapter 1). The ASF is a Delaware
# membership corporation, so its bylaws operate within this statute. These
# sources are only searched when a query mentions Delaware.
_DELAWARE_GCL_SUBCHAPTERS: list[tuple[str, str, str, str]] = [
    ("formation", "sc01", "Subchapter I. Formation",
     "Incorporators, certificate of incorporation, bylaws, and corporate formation"),
    ("powers", "sc02", "Subchapter II. Powers",
     "General and specific powers of Delaware corporations"),
    ("registered_office", "sc03", "Subchapter III. Registered Office and Registered Agent",
     "Registered office and registered agent requirements"),
    ("directors_officers", "sc04", "Subchapter IV. Directors and Officers",
     "Boards of directors, officers, committees, meetings, and indemnification"),
    ("stock_dividends", "sc05", "Subchapter V. Stock and Dividends",
     "Classes of stock, stock issuance, dividends, and redemption"),
    ("stock_transfers", "sc06", "Subchapter VI. Stock Transfers",
     "Transfer and registration of stock and restrictions on transfer"),
    ("meetings_voting", "sc07", "Subchapter VII. Meetings, Elections, Voting and Notice",
     "Stockholder and member meetings, elections, voting, proxies, consent, and notice"),
    ("amendments", "sc08", "Subchapter VIII. Amendment of Certificate of Incorporation; Changes in Capital and Capital Stock",
     "Amending the certificate of incorporation and changes in capital stock"),
    ("merger_conversion", "sc09", "Subchapter IX. Merger, Consolidation or Conversion",
     "Mergers, consolidations, and conversions of corporations and other entities"),
    ("dissolution", "sc10", "Subchapter X. Sale of Assets, Dissolution and Winding Up",
     "Sale of assets, dissolution, and winding up of corporations"),
    ("insolvency", "sc11", "Subchapter XI. Insolvency; Receivers and Trustees",
     "Insolvency, receivers, and trustees"),
    ("renewal_revival", "sc12", "Subchapter XII. Renewal, Revival, Extension and Restoration",
     "Renewal, revival, extension, and restoration of certificates of incorporation"),
    ("suits", "sc13", "Subchapter XIII. Suits Against Corporations, Directors, Officers or Stockholders",
     "Suits against corporations, directors, officers, or stockholders"),
    ("close_corporations", "sc14", "Subchapter XIV. Close Corporations; Special Provisions",
     "Special provisions for close corporations"),
    ("public_benefit", "sc15", "Subchapter XV. Public Benefit Corporations",
     "Public benefit corporations"),
    ("foreign_corporations", "sc16", "Subchapter XVI. Foreign Corporations",
     "Foreign corporations doing business in Delaware"),
    ("domestication_transfer", "sc17", "Subchapter XVII. Domestication and Transfer",
     "Domestication and transfer of non-Delaware entities"),
    ("miscellaneous", "sc18", "Subchapter XVIII. Miscellaneous Provisions",
     "Miscellaneous provisions including nonstock and membership corporations"),
]

POLICY_SOURCES.update({
    f"delaware_gcl_{slug}": {
        "title": f"Delaware General Corporation Law — {title}",
        "url": f"https://delcode.delaware.gov/title8/c001/{path}/index.html",
        "section": "Delaware Law",
        "description": f"{description} (Delaware Code Title 8, Chapter 1)",
        "search_requires": "delaware",
    }
    for slug, path, title, description in _DELAWARE_GCL_SUBCHAPTERS
})
